# Generated by Django 3.2.6 on 2022-03-11 15:24

from django.db import migrations, models


def copy_id_to_timeslot(apps, schema_editor):
    NotificationProfile = apps.get_model("argus_notificationprofile", "NotificationProfile")

    profiles = NotificationProfile.objects.all()
    for profile in profiles:
        profile.timeslot_id = profile.id

    NotificationProfile.objects.bulk_update(objs=profiles, fields=["timeslot"])


def delete_multi_use_timeslot_profiles(apps, schema_editor):
    Timeslot = apps.get_model("argus_notificationprofile", "Timeslot")

    timeslots = Timeslot.objects.prefetch_related("notification_profiles").annotate(
        num_profiles=models.Count("notification_profiles")
    )
    for timeslot in timeslots.filter(num_profiles__gt=1):
        profiles = timeslot.notification_profiles.order_by("pk").all()
        first_profile_id = profiles[0].id
        profiles.exclude(id=first_profile_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("argus_notificationprofile", "0005_destinationconfig_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationprofile",
            name="timeslot",
            field=models.AutoField(
                primary_key=True,
            ),
        ),
        migrations.RenameField(
            model_name="notificationprofile",
            old_name="timeslot",
            new_name="id",
        ),
        migrations.AddField(
            model_name="notificationprofile",
            name="timeslot",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="notification_profiles",
                to="argus_notificationprofile.timeslot",
            ),
        ),
        migrations.AddField(
            model_name="notificationprofile",
            name="name",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="notificationprofile",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="unique_name_per_user"),
        ),
        migrations.RunPython(copy_id_to_timeslot, delete_multi_use_timeslot_profiles),
        migrations.AlterField(
            model_name="notificationprofile",
            name="timeslot",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="notification_profiles",
                to="argus_notificationprofile.timeslot",
            ),
        ),
    ]
